//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WadaanSystemManager.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LangText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LangText() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WadaanSystemManager.Resources.LangText", typeof(LangText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACTIVE MEMBER.
        /// </summary>
        public static string ACTIVECUSTOMER {
            get {
                return ResourceManager.GetString("ACTIVECUSTOMER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Member Record.
        /// </summary>
        public static string AddCustomerRecord {
            get {
                return ResourceManager.GetString("AddCustomerRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Transaction Record.
        /// </summary>
        public static string AddTransactionRecord {
            get {
                return ResourceManager.GetString("AddTransactionRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Member(s) record list.
        /// </summary>
        public static string AllCustomersrecordlist {
            get {
                return ResourceManager.GetString("AllCustomersrecordlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Transaction(s) record list.
        /// </summary>
        public static string AllTransactionrecordlist {
            get {
                return ResourceManager.GetString("AllTransactionrecordlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        public static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Language.
        /// </summary>
        public static string ChangeLanguage {
            get {
                return ResourceManager.GetString("ChangeLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Name.
        /// </summary>
        public static string ChooseName {
            get {
                return ResourceManager.GetString("ChooseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit/Debit.
        /// </summary>
        public static string CreditDebit {
            get {
                return ResourceManager.GetString("CreditDebit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CURENT MONTH.
        /// </summary>
        public static string CURENTMONTH {
            get {
                return ResourceManager.GetString("CURENTMONTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CURENT WEEK.
        /// </summary>
        public static string CURENTWEEK {
            get {
                return ResourceManager.GetString("CURENTWEEK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CURENT YEAR.
        /// </summary>
        public static string CURENTYEAR {
            get {
                return ResourceManager.GetString("CURENTYEAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member.
        /// </summary>
        public static string Customer {
            get {
                return ResourceManager.GetString("Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MEMBER AREA.
        /// </summary>
        public static string CustomerArea {
            get {
                return ResourceManager.GetString("CustomerArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member Dashboard.
        /// </summary>
        public static string CustomerDashboard {
            get {
                return ResourceManager.GetString("CustomerDashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member List.
        /// </summary>
        public static string CustomerList {
            get {
                return ResourceManager.GetString("CustomerList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member Module.
        /// </summary>
        public static string CustomerModule {
            get {
                return ResourceManager.GetString("CustomerModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member Name.
        /// </summary>
        public static string CustomerName {
            get {
                return ResourceManager.GetString("CustomerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member Record.
        /// </summary>
        public static string CustomerRecord {
            get {
                return ResourceManager.GetString("CustomerRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MEMBER(S).
        /// </summary>
        public static string CUSTOMERS {
            get {
                return ResourceManager.GetString("CUSTOMERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MEMBER WISE RECORD.
        /// </summary>
        public static string CUSTOMERWISERECORD {
            get {
                return ResourceManager.GetString("CUSTOMERWISERECORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DAILY TRANSCATION.
        /// </summary>
        public static string DAILYTRANSCATION {
            get {
                return ResourceManager.GetString("DAILYTRANSCATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DashBoard.
        /// </summary>
        public static string DashBoard {
            get {
                return ResourceManager.GetString("DashBoard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Paid.
        /// </summary>
        public static string DatePaid {
            get {
                return ResourceManager.GetString("DatePaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DAY/WEEK/MONT/YEAR WISE (CREDIT-DEBIT).
        /// </summary>
        public static string DAYWEEKMONTYEARWISE {
            get {
                return ResourceManager.GetString("DAYWEEKMONTYEARWISE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DEBIT/CREDIT AREA.
        /// </summary>
        public static string DEBITCREDITAREA {
            get {
                return ResourceManager.GetString("DEBITCREDITAREA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to District.
        /// </summary>
        public static string District {
            get {
                return ResourceManager.GetString("District", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address.
        /// </summary>
        public static string EmailAddress {
            get {
                return ResourceManager.GetString("EmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date.
        /// </summary>
        public static string EndDate {
            get {
                return ResourceManager.GetString("EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Father Name.
        /// </summary>
        public static string FName {
            get {
                return ResourceManager.GetString("FName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot Your Password.
        /// </summary>
        public static string ForgotYourPassword {
            get {
                return ResourceManager.GetString("ForgotYourPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        public static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IN-ACTIVE CUSTOMER.
        /// </summary>
        public static string INACTIVECUSTOMER {
            get {
                return ResourceManager.GetString("INACTIVECUSTOMER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile No.
        /// </summary>
        public static string MobileNo {
            get {
                return ResourceManager.GetString("MobileNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NIC.
        /// </summary>
        public static string NIC {
            get {
                return ResourceManager.GetString("NIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passport No.
        /// </summary>
        public static string PassportNo {
            get {
                return ResourceManager.GetString("PassportNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profession.
        /// </summary>
        public static string Profession {
            get {
                return ResourceManager.GetString("Profession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Province.
        /// </summary>
        public static string Province {
            get {
                return ResourceManager.GetString("Province", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qualification.
        /// </summary>
        public static string Qualification {
            get {
                return ResourceManager.GetString("Qualification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remarks.
        /// </summary>
        public static string Remarks {
            get {
                return ResourceManager.GetString("Remarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rememberme.
        /// </summary>
        public static string Rememberme {
            get {
                return ResourceManager.GetString("Rememberme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string search {
            get {
                return ResourceManager.GetString("search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT YEAR WISE DATE.
        /// </summary>
        public static string SELECTYEARWISEDATE {
            get {
                return ResourceManager.GetString("SELECTYEARWISEDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In.
        /// </summary>
        public static string SignIn {
            get {
                return ResourceManager.GetString("SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign up. It is fast and easy.
        /// </summary>
        public static string SignupFasteasy {
            get {
                return ResourceManager.GetString("SignupFasteasy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign up now.
        /// </summary>
        public static string Signupnow {
            get {
                return ResourceManager.GetString("Signupnow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date.
        /// </summary>
        public static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAWA Admin Dashboard.
        /// </summary>
        public static string StoreAdminDashboard {
            get {
                return ResourceManager.GetString("StoreAdminDashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SubTribe.
        /// </summary>
        public static string SubTribe {
            get {
                return ResourceManager.GetString("SubTribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODAY.
        /// </summary>
        public static string TODAY {
            get {
                return ResourceManager.GetString("TODAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TOTAL CREDIT.
        /// </summary>
        public static string TOTALCREDIT {
            get {
                return ResourceManager.GetString("TOTALCREDIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TOTAL MEMBER.
        /// </summary>
        public static string TOTALCUSTOMER {
            get {
                return ResourceManager.GetString("TOTALCUSTOMER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TOTAL DEBIT.
        /// </summary>
        public static string TOTALDEBIT {
            get {
                return ResourceManager.GetString("TOTALDEBIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TOTAL REMAINING.
        /// </summary>
        public static string TOTALREMAINING {
            get {
                return ResourceManager.GetString("TOTALREMAINING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TOTAL STORE.
        /// </summary>
        public static string TOTALSTORE {
            get {
                return ResourceManager.GetString("TOTALSTORE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction Add | Update | Delete.
        /// </summary>
        public static string TransactionAddUpdateDelete {
            get {
                return ResourceManager.GetString("TransactionAddUpdateDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction List.
        /// </summary>
        public static string TransactionList {
            get {
                return ResourceManager.GetString("TransactionList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction Module.
        /// </summary>
        public static string TransactionModule {
            get {
                return ResourceManager.GetString("TransactionModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction Record.
        /// </summary>
        public static string TransactionRecord {
            get {
                return ResourceManager.GetString("TransactionRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction(S).
        /// </summary>
        public static string TransactionS {
            get {
                return ResourceManager.GetString("TransactionS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction Type.
        /// </summary>
        public static string TransactionType {
            get {
                return ResourceManager.GetString("TransactionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tribe.
        /// </summary>
        public static string Tribe {
            get {
                return ResourceManager.GetString("Tribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        public static string Upload {
            get {
                return ResourceManager.GetString("Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Signature.
        /// </summary>
        public static string UploadSignature {
            get {
                return ResourceManager.GetString("UploadSignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
    }
}
